import 'package:flutter/material.dart';
import 'package:prohealth/app/resources/theme_manager.dart';
import 'package:prohealth/presentation/screens/hr_module/manage/const_wrap_widget.dart';
import 'package:prohealth/presentation/screens/hr_module/manage/widgets/icon_button_constant.dart';
import 'package:prohealth/presentation/screens/hr_module/manage/widgets/row_container_widget_const.dart';

class TerminationHeadTabbar extends StatelessWidget {
  const TerminationHeadTabbar({super.key});

  @override
  Widget build(BuildContext context) {
    return WrapWidget(childern: List.generate(2, (index){
      return Padding(
        padding:const EdgeInsets.symmetric(horizontal: 30,vertical: 20),
        child: Container(
          width: MediaQuery.of(context).size.width/2.3,
          decoration: BoxDecoration(
            boxShadow: [
              BoxShadow(
                color: Colors.grey.withOpacity(0.5),
                spreadRadius: 1,
                blurRadius: 4,
                offset: Offset(0, 4),
              ),
            ],
            color: Colors.white,
            borderRadius: BorderRadius.all(Radius.circular(12)),
          ),
          height:  MediaQuery.of(context).size.height/2.5,
          child: Padding(
            padding: EdgeInsets.symmetric(
              horizontal: MediaQuery.of(context).size.width / 120,
              vertical: MediaQuery.of(context).size.height / 120,
            ),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
                const Row(
                  children: [
                    Text('Employee #1',
                      style: TextStyle(
                        fontFamily: 'FiraSans',
                        fontSize: 13,
                        color: Color(0xFF333333),
                        fontWeight: FontWeight.w500,
                      ),),
                  ],),
                SizedBox(height: MediaQuery.of(context).size.height/50,),
                Row(
                  // mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text('Name',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),

                            Text('Date of Termination',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('Date of Resignation',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('Date of Hire',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('Status',
                                style: ThemeManager.customTextStyle(context)),
                            Text('Position',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('Phone No.',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('Rehirable',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('Final Address',
                                style: ThemeManager.customTextStyle(context)),
                          ],
                        ),
                        SizedBox(width: 25,),
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text('Albert Wilson',
                              style: ThemeManagerDark.customTextStyle(context),),
                            const SizedBox(height: 10,),
                            Text('01-04-23',
                              style: ThemeManagerDark.customTextStyle(context),),
                            const SizedBox(height: 10,),
                            Text('24-03-23',
                              style: ThemeManagerDark.customTextStyle(context),),
                            const SizedBox(height: 10,),
                            Text('15-01-20',
                              style: ThemeManagerDark.customTextStyle(context),),
                            Text('Inactive',
                              style: ThemeManagerDark.customTextStyle(context),),
                            const SizedBox(height: 10,),
                            Text('Developer',
                              style: ThemeManagerDark.customTextStyle(context),),
                            const SizedBox(height: 10,),
                            Text('123456789',
                              style: ThemeManagerDark.customTextStyle(context),),
                            const SizedBox(height: 10,),
                            Text('Yes',
                              style: ThemeManagerDark.customTextStyle(context),),
                            const SizedBox(height: 10,),
                            Text('151 Bloor ST. West Toranto,\nOstanio, Canada',
                              style: ThemeManagerDark.customTextStyle(context),),
                          ],
                        ),
                      ],
                    ),
                    SizedBox(width: MediaQuery.of(context).size.width / 10,),
                    Row(
                      children: [
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          mainAxisAlignment: MainAxisAlignment.start,
                          children: [
                            Text('Type',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('Reason',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('Final Paycheck',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('Date',
                                style: ThemeManager.customTextStyle(context)),
                            Text('Gross Pay',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('Net Pay',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('Methods',
                                style: ThemeManager.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('Materials',
                                style: ThemeManager.customTextStyle(context)),
                          ],
                        ),
                        SizedBox(width: 25,),
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text('',
                              style: ThemeManagerDark.customTextStyle(context),),
                            const SizedBox(height: 10,),
                            Text('Personal',
                              style: ThemeManagerDark.customTextStyle(context),),
                            const SizedBox(height: 10,),
                            Text('\$1400',
                                style: ThemeManagerDark.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text('15-05-23',
                                style: ThemeManagerDark.customTextStyle(context)),
                            Text('\$1500',
                              style: ThemeManagerDark.customTextStyle(context),),
                            const SizedBox(height: 10,),
                            Text('\$1200',
                              style: ThemeManagerDark.customTextStyle(context),),
                            const SizedBox(height: 10,),
                            Text(' ',
                                style: ThemeManagerDark.customTextStyle(context)),
                            const SizedBox(height: 10,),
                            Text(' ',
                                style: ThemeManagerDark.customTextStyle(context)),
                          ],
                        ),
                      ],
                    )


                  ],
                ),
              ],
            ),
          ),
        ),
      );
    }));
    //   Expanded(
    //   child: Container(
    //     // color: Colors.lightGreenAccent,
    //     child: Column(
    //       children: [
    //         TwoContainersRow(
    //           height: 300,
    //           child1: Column(
    //             mainAxisAlignment: MainAxisAlignment.start,
    //             children: [
    //               const Row(
    //                 children: [
    //                 Text('Employee #1',
    //                   style: TextStyle(
    //                     fontFamily: 'FiraSans',
    //                     fontSize: 13,
    //                     color: Color(0xFF333333),
    //                     fontWeight: FontWeight.w500,
    //                   ),),
    //               ],),
    //               SizedBox(height: MediaQuery.of(context).size.height/50,),
    //               Row(
    //                // mainAxisAlignment: MainAxisAlignment.spaceBetween,
    //                 children: [
    //                   Row(
    //                     mainAxisAlignment: MainAxisAlignment.spaceBetween,
    //                     crossAxisAlignment: CrossAxisAlignment.start,
    //                     children: [
    //                       Column(
    //                         crossAxisAlignment: CrossAxisAlignment.start,
    //                         children: [
    //                           Text('Name',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //
    //                           Text('Date of Termination',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Date of Resignation',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Date of Hire',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Status',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           Text('Position',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Phone No.',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Rehirable',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Final Address',
    //                               style: ThemeManager.customTextStyle(context)),
    //                         ],
    //                       ),
    //                       SizedBox(width: 25,),
    //                       Column(
    //                         crossAxisAlignment: CrossAxisAlignment.start,
    //                         children: [
    //                           Text('Albert Wilson',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('01-04-23',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('24-03-23',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('15-01-20',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           Text('Inactive',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('Developer',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('123456789',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('Yes',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('151 Bloor ST. West Toranto,\nOstanio, Canada',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                         ],
    //                       ),
    //                     ],
    //                   ),
    //                   SizedBox(width: MediaQuery.of(context).size.width / 10,),
    //                   Row(
    //                     children: [
    //                       Column(
    //                         crossAxisAlignment: CrossAxisAlignment.start,
    //                         mainAxisAlignment: MainAxisAlignment.start,
    //                         children: [
    //                           Text('Type',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Reason',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Final Paycheck',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Date',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           Text('Gross Pay',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Net Pay',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Methods',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Materials',
    //                               style: ThemeManager.customTextStyle(context)),
    //                         ],
    //                       ),
    //                       SizedBox(width: 25,),
    //                       Column(
    //                         crossAxisAlignment: CrossAxisAlignment.start,
    //                         children: [
    //                           Text('',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('Personal',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('\$1400',
    //                               style: ThemeManagerDark.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('15-05-23',
    //                               style: ThemeManagerDark.customTextStyle(context)),
    //                           Text('\$1500',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('\$1200',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text(' ',
    //                               style: ThemeManagerDark.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text(' ',
    //                               style: ThemeManagerDark.customTextStyle(context)),
    //                         ],
    //                       ),
    //                     ],
    //                   )
    //
    //
    //                 ],
    //               ),
    //             ],
    //           ),
    //           child2: Column(
    //             mainAxisAlignment: MainAxisAlignment.start,
    //             children: [
    //               const Row(children: [
    //                 Text('Employee #2',
    //                   style: TextStyle(
    //                     fontFamily: 'FiraSans',
    //                     fontSize: 13,
    //                     color: Color(0xFF333333),
    //                     fontWeight: FontWeight.w500,
    //                   ),),
    //               ],),
    //               SizedBox(height: MediaQuery.of(context).size.height/50,),
    //               Row(
    //                 // mainAxisAlignment: MainAxisAlignment.spaceBetween,
    //                 children: [
    //                   Row(
    //                     mainAxisAlignment: MainAxisAlignment.spaceBetween,
    //                     crossAxisAlignment: CrossAxisAlignment.start,
    //                     children: [
    //                       Column(
    //                         crossAxisAlignment: CrossAxisAlignment.start,
    //                         children: [
    //                           Text('Degree',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //
    //                           Text('Date of Termination',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Date of Resignation',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Date of Hire',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Status',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           Text('Position',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Phone No.',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Rehirable',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Final Address',
    //                               style: ThemeManager.customTextStyle(context)),
    //                         ],
    //                       ),
    //                       SizedBox(width: 25,),
    //                       Column(
    //                         crossAxisAlignment: CrossAxisAlignment.start,
    //                         children: [
    //                           Text('Albert Wilson',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('01-04-23',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('24-03-23',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('15-01-20',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           Text('Inactive',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('Developer',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('123456789',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('Yes',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('151 Bloor ST. West Toranto,\nOstanio, Canada',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                         ],
    //                       ),
    //                     ],
    //                   ),
    //                   SizedBox(width: MediaQuery.of(context).size.width / 10,),
    //                   Row(
    //                     children: [
    //                       Column(
    //                         crossAxisAlignment: CrossAxisAlignment.start,
    //                         mainAxisAlignment: MainAxisAlignment.start,
    //                         children: [
    //                           Text('Type',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Reason',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Final Paycheck',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Date',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           Text('Gross Pay',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Net Pay',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Methods',
    //                               style: ThemeManager.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('Materials',
    //                               style: ThemeManager.customTextStyle(context)),
    //                         ],
    //                       ),
    //                       SizedBox(width: 25,),
    //                       Column(
    //                         crossAxisAlignment: CrossAxisAlignment.start,
    //                         children: [
    //                           Text('',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('Personal',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('\$1400',
    //                               style: ThemeManagerDark.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text('15-05-23',
    //                               style: ThemeManagerDark.customTextStyle(context)),
    //                           Text('\$1500',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text('\$1200',
    //                             style: ThemeManagerDark.customTextStyle(context),),
    //                           const SizedBox(height: 10,),
    //                           Text(' ',
    //                               style: ThemeManagerDark.customTextStyle(context)),
    //                           const SizedBox(height: 10,),
    //                           Text(' ',
    //                               style: ThemeManagerDark.customTextStyle(context)),
    //                         ],
    //                       ),
    //                     ],
    //                   )
    //
    //
    //                 ],
    //               ),
    //             ],
    //           ),
    //         ),
    //       ],
    //     ),
    //   ),
    // );
  }
}



